/* INSERT "Tabla(valores) VALUES (Los valores que tu quieres agregar)" */

CREATE TABLE CANCION
(

    ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    NOMBRE_CANCION VARCHAR2(100),

    DURACION_SEGUNDOS NUMERIC

);

CREATE TABLE ARTISTA
(

    ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    NOMBRE_ARTISTA VARCHAR2(50)

);

CREATE TABLE GENERO
(

    ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    NOMBRE_GENERO VARCHAR2(40) UNIQUE NOT NULL 

);

CREATE TABLE ALBUM
(

    ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    NOMBRE_ALBUM VARCHAR(100)

);