@02.Tablas_principales.sql;

INSERT INTO CANCION(NOMBRE_CANCION, DURACION_SEGUNDOS) VALUES ('CHUPA EL PERRO', 120);

INSERT INTO CANCION(NOMBRE_CANCION, DURACION_SEGUNDOS) VALUES ('TROLEADO TROLEADO', 1000);

INSERT INTO CANCION(NOMBRE_CANCION, DURACION_SEGUNDOS) VALUES ('LIMONES 4K DEL RUBIUSOMG', 230);

INSERT INTO ALBUM(NOMBRE_ALBUM) VALUES ('LOS RUBIUS ESTAN DE VUELTA');

INSERT INTO GENERO(NOMBRE_GENERO) VALUES ('Pop');

INSERT INTO GENERO(NOMBRE_GENERO) VALUES ('Rock');

INSERT INTO ARTISTA(NOMBRE_ARTISTA) VALUES ('German Garmendia');

INSERT INTO ARTISTA(NOMBRE_ARTISTA) VALUES ('ElRubiusOMG');

INSERT INTO CANCION_ARTISTA(ID_CANCION, ID_ARTISTA) VALUES (1, 1);

INSERT INTO CANCION_ARTISTA(ID_CANCION, ID_ARTISTA) VALUES (2, 2);

INSERT INTO CANCION_ARTISTA(ID_CANCION, ID_ARTISTA) VALUES (3, 2);

INSERT INTO CANCION_GENERO(ID_CANCION, ID_GENERO) VALUES (1, 1);

INSERT INTO CANCION_GENERO(ID_CANCION, ID_GENERO) VALUES (2, 1);

INSERT INTO CANCION_GENERO(ID_CANCION, ID_GENERO) VALUES (3, 2);

INSERT INTO ALBUM_CANCION(ID_CANCION, ID_ALBUM) VALUES (2, 1);

INSERT INTO ALBUM_CANCION(ID_CANCION, ID_ALBUM) VALUES (3, 1);

SELECT * FROM CANCION;

Select * from ARTISTA;

SELECT * FROM ALBUM;

SELECT * FROM CANCION_ARTISTA;

SELECT * FROM CANCION_GENERO;

SELECT * FROM ALBUM_CANCION;

COMMIT;