DROP TABLE USUARIO_GENERAL CASCADE CONSTRAINT;

DROP TABLE PLAYLIST CASCADE CONSTRAINT;

DROP TABLE TIPO_USUARIO CASCADE CONSTRAINT;

DROP TABLE ESTADO_VISIBILIDAD CASCADE CONSTRAINT;

DROP TABLE TIENE_CANAL_ASOCIADO CASCADE CONSTRAINT;

DROP TABLE CASCADE CONSTRAINT;

DROP TABLE CASCADE CONSTRAINT;

DROP TABLE CASCADE CONSTRAINT;

DROP TABLE CASCADE CONSTRAINT;

DROP TABLE CASCADE CONSTRAINT;

DROP TABLE CASCADE CONSTRAINT;

DROP TABLE CASCADE CONSTRAINT;

COMMIT;

ROLLBACK;