CREATE TABLE TIPO_USUARIO
(

    ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    NOMBRE_TIPO VARCHAR2(30) NOT NULL UNIQUE

);

CREATE TABLE ESTADO_VISIBILIDAD 
(

    ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    NOMBRE_ESTADO VARCHAR2(30)

);

CREATE TABLE TIENE_CANAL_ASOCIADO
(

    ID NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    SI__NO CHAR(1) NOT NULL UNIQUE


);
COMMIT;

ROLLBACK;